# Ham or Spam?

In [37]:
%load_ext autoreload
%autoreload 2

In [1]:
# when installing nltk for the first time we need to also download a few built in libraries
#!pip install nltk
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Abize\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Abize\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Abize\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [3]:
import pandas as pd

df = pd.read_csv("emails.csv")

df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

The dataset is made up of email that are classified as ham [0] or spam[1]. You need to clean the dataset before training a prediction model.

## Remove Punctuation

👇 Create a function to remove the punctuation. Apply it to the entire data and add the output as a new column in the dataframe called `clean_text`

In [6]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [7]:
def remove_punctuation(txt):
    txt_nopunct = "".join([c for c in txt if c not in string.punctuation])
    return txt_nopunct
#remove_punctuation(df.text)

## Lower Case

👇 Create a function to lower case the text. Apply it to `clean_text`

In [8]:
df['clean_text'] = df['text'].apply(lambda x: remove_punctuation(x))

## Remove Numbers

👇 Create a function to remove numbers from the text. Apply it to `clean_text`

In [26]:
#ETAPES DE PRE TRAITEMENT
#Natural Language Processing

#Importing the librarie
import numpy as np
import pandas as pd
import re
import nltk
nltk.download('stopwords')
#concernant des mots vides
from nltk.corpus import stopwords
#il y'a d'autres mots qui ne sont pas utiles
from nltk.stem.porter import PorterStemmer

[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


In [40]:
import NLP_exerice1

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Abize\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [45]:
#importing dadaset
df = pd.read_csv("emails.csv", delimiter=',')

df['clean_text'] = NLP_exerice1.preproccessing(df.text)

c:\Users\Abize\OneDrive\Bureau\SIMPLON\Brief_13\01-Ham-or-Spam\Rendre\NLP_exerice1.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  series[i] = review


In [46]:
df['clean_text']

0       subject natur irresist corpor ident lt realli ...
1       subject stock trade gunsling fanni merril muzo...
2       subject unbeliev new home made easi im want sh...
3       subject color print special request addit info...
4       subject not money get softwar cd softwar compa...
                              ...                        
5723    subject research develop charg gpg forward shi...
5724    subject receipt visit jim thank invit visit ls...
5725    subject enron case studi updat wow day super t...
5726    subject interest david pleas call shirley cren...
5727    subject news aurora updat aurora version faste...
Name: clean_text, Length: 5728, dtype: object

In [ ]:


#tous les mots sont stockes dans cette liste
corpus = []

for i in range(len(df)):
    #supression de tous type de ponctuation 
    #il y'aura un espace entre les mots
    review = re.sub('[^a-zA-Z]'," ", df['text'][i])
    #mettre en minuscule
    review = review.lower()
    #faire une simplification du mot par la racine: permet d'optimiser la dimensionnalité de la matrice
    #qui sera creer plus tard avec un sac des mots
    review = review.split()
    #on instancie la classe
    ps = PorterStemmer()
    #Application du radical en enlevant la liste de tous les petits mots
    all_stopwords = stopwords.words('english')
    #se debarasse des mots negatif
    all_stopwords.remove("not")
    # Pour chaque mot on va itere en se debarassant des tous les mots vides
    review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
    #on va reunir la liste ; avec un espace qui essayera de separer les mots : Eviter que les mots soient coles
    #Permet d'eviter que l'on mette un separateur
    review = ' '.join(review)
    #On va charger review propre dans la liste des mots(corpus)
    corpus.append(review)
    #Bravo le texte a été bien netoye et pres à etre utiliser
#print(corpus)



In [27]:
#CREATION DU MODEL ET APPLIQUER NLP POUR PREDIRE LES REVIEW/ soit c'est un spam ou non
#Creating the Bag of words model
#Vectorisation des mots  : Creer un sac des vecteurs des mots
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()
y = df.spam

In [22]:

#Nous allons diviser ce sac des mots en train et test
#splitting the df into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [24]:

#Training the Naive Bayes model on the training set
from sklearn.naive_bayes import GaussianNB

classifier = GaussianNB()
classifier.fit(X_train, y_train)

#Prediction the Test set resultats
y_pred = classifier.predict(X_test)
y_pred

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)

In [29]:
#Training the Naive Bayes model on the training set
from sklearn.naive_bayes import MultinomialNB

classifier_multi = MultinomialNB()
classifier_multi.fit(X_train, y_train)

#Prediction the Test set resultats
y_pred_multi = classifier_multi.predict(X_test)
y_pred_multi

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [30]:
#Pour les performance du model on va utiliser la matrix de confusion
# Making the confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_multi)
print(cm)
accuracy_score(y_test, y_pred_multi)

[[868  21]
 [  5 252]]


0.9773123909249564

In [25]:

#Pour les performance du model on va utiliser la matrix de confusion
# Making the confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[833  56]
 [ 16 241]]


0.93717277486911

In [11]:
print(f'nombre de lignes: {len(df)} rows, nombre de colonnes: {len(df.columns)} columns')

nombre de lignes: 5728 rows, nombre de colonnes: 2 columns


## Remove StopWords

👇 Create a function to remove stopwords from the text. Apply it to `clean_text`.

## Lemmatize

👇 Create a function to lemmatize the text. Make sure the output is a single string, not a list of words. Apply it to `clean_text`.

## Bag-of-words Modelling

👇 Vectorize the `clean_text` to a Bag-of-Words representation with a default CountVectorizer . Save as `X_bow`.

👇 Cross-validate a MultinomialNB model with the Bag-of-words. Score the model's accuracy.

⚠️ Please push the exercise once you are done 🙃

## 🏁 